name: "GMC-300S Monitor"
description: "Interface for reading data from a GMC-300S radiation monitor"
version: "1.0.0"
slug: "gmc300s"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  port: "/dev/ttyUSB0"
  baudrate: 57600
  repeat: "30"
schema:
  port: str
  baudrate: int
  repeat: int
init: false
startup: once
uart: true
host_network: true
video: false
homeassistant_api: true
hassio_api: false